#!/bin/bash
# Copyright Amazon.com, Inc. or its affiliates. All Rights Reserved.
# SPDX-License-Identifier: Apache-2.0

PYTHONPATH=./source/lambdas/ pytest \
    tests/lambdas/ \
    --cov=source/lambdas/ \
    --cov-report term-missing \
    --looponfail
